name: help_yourself_app
description: Mobile application for self-psychotherapy.
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^1.5.3
  get_it: ^7.2.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  onesignal_flutter: ^3.2.8
  flutter_secure_storage: ^5.0.2
  objectbox: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true